import time

name = input("What is your name? ")
print("Welcome "+ name)
time.sleep(2)
print ("Here are the instructions for cooking a pasta:")
time.sleep(2)
print ("First , Boil the water")
time.sleep(2)
print ("Second, wait for 5 min")
time.sleep(2)
print ("Third, add salt")
time.sleep(2)
print ("Fouth, add the pasta")
time.sleep(2)
print ("Fifth, cook the pasta for 15 min ")
time.sleep(2)
print ("Sixth, remove the pasta.")
time.sleep(2)
print ("its done!")
